export interface Tour {
  id?: number;
  name?: string;
  price?: number;
  category_Name?: string;
  categoy?:any;
  category_Id?:number;
  description: string;
  image?: string;
  quantity_limit?: number;
  departure_Time?: Date;
  rating?: number | null;
  type?: boolean | false;
  range_time?: number;
  transportation_Name?: string;
  transportation_ID?: number;
  transportation? : any;
  discount?: number;
  departure_location?: string;
  urlImage?: string[];
  isActive?: number;
  createAt?: Date;
  createBy?: string;
  updateAt?: Date;
  updateBy?: string;
  staff_Id?: number;
}

// seed data

export const tours: Tour[] = [
  {
    id: 1,
    name: 'Ha Long Bay',
    price: 768,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 4,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 2,
    name: 'Hai Phong',
    price: 1000,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 3,
    name: 'Ha Long Bay',
    price: 556,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 3,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 4,
    name: 'Ha Long Bay',
    price: 2356,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 2,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 5,
    name: 'Ha Long Bay',
    price: 5656,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 6,
    name: 'Ha Long Bay',
    price: 453,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 7,
    name: 'Ha Long Bay',
    price: 452,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 8,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 9,
    name: 'Ha Long Bay sadsad  dasd sadsad asdsd',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 10,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 11,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 12,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 14,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 9,
    name: 'Ha Long Bay',
    price: 1000,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 9,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 10,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 11,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 12,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
  {
    id: 14,
    name: 'Ha Long Bay',
    price: 123,
    category_Name: 'beach',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc. Cras elementum pretium est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras sollicitudin, tellus vitae condimentum egestas, libero dolor auctor tellus, eu consectetur neque elit quis nunc.Cras elementum pretium est.',
    image: '../../assets/images/Rectangle 19377.jpg',
    quantity_limit: 40,
    rating: 5,
    type: false,
    transportation_Name: 'plane',
    isActive: 1,
    createAt: new Date(),
    createBy: '1234',
    updateAt: new Date(),
    updateBy: '1234',
  },
];
