version: "3.8"
services:
  nginx:
    image: nginx:1.23.3
    ports:
      - 4200:80
    volumes:
      - ./frontend/dist/frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  api:
        build:
          context: ./backend
          dockerfile: Dockerfile
        ports:
          - "7110:80"
        depends_on:
          - db
          - cache  

  db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        volumes:
          - ./data:/var/opt/mssql/data
          - ./log:/var/opt/mssql/log
          - ./secrets:/var/opt/mssql/secrets 
        environment:
            SA_PASSWORD: "Datvip9x@"
            ACCEPT_EULA: "Y"
  cache:
        image: redis:6.2-alpine
        restart: always
        ports:
          - "6379:6379"    